baseURL = "https://ecac01.github.io/"
title = "Elizabethton Counseling & Arts Center"
author = "Brandon Cole, M. Div., M.A, LPC/MHSP"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true
hasCJKLanguage= false

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.jpg"
    alt = "ECAC Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Elizabethton Counseling & Arts Center"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Elizabethton Counseling & Arts Center"
    meta_og_title = "Elizabethton Counseling & Arts Center"
    meta_og_type = "website"
    meta_og_url = "https://www.elizabethtoncac.com"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Elizabethton Counseling & Arts Center"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]


  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "Meet Our Providers"
    name = "Meet Our Providers"
    url = "/providers/"
    weight = 2

    [[menu.main]]
    identifier = "Services"
    name = "Services"
    url = "/services/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

    [[menu.main]]
    identifier = "Insurance & Financial"
    name = "Insurance & Financial"
    url = "/financial/"
    weight = 5

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 6

    [[menu.main]]
    identifier = "Video"
    name = "Video"
    url = "https://youtube.com/@brandoncole7049"
    weight = 7

    [[menu.main]]
    identifier = "Portal Access"
    name = "Portal Access"
    url = "https://www.therapyportal.com/p/strummerville"
    weight = 8

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
